### ISSUE TITLE
New Functionality: HTML default color names

### ISSUE THREAD

**Issue by guisantosfr** [guisantosfr/Random-Color-Generator#1]
The enhancement needed to the project is to add the HTML color names as a new functionality.

**Comment by ORKO06** [comment]
I would like to work on it

**Comment by guisantosfr** [comment]
Ok. Go on!

**Comment by guisantosfr** [comment]
Approved. Nice work!

**Comment by ORKO06** [comment]
Thank you for giving me the chance. I learned something new
